
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

/** @typedef {"modern" | "baseline" | "default"} EmbeddedAddonVariant */

/**
 * @typedef {Object} EmbeddedAddonFile
 * @property {EmbeddedAddonVariant} variant
 * @property {string} filename
 * @property {number} size
 * @property {string=} filePath
 */

/**
 * @typedef {Object} EmbeddedAddonArchive
 * @property {"tar.gz"} format
 * @property {string} filename
 * @property {string} filePath
 */

/**
 * @typedef {Object} EmbeddedAddon
 * @property {string} platformTag
 * @property {string} version
 * @property {EmbeddedAddonFile[]} files
 * @property {EmbeddedAddonArchive=} archive
 */

import archivePath from "../native/embedded-addons.win32-x64.tar.gz" with { type: "file" };

export const embeddedAddon = {
	platformTag: "win32-x64",
	version: "17.0.8",
	archive: {
		format: "tar.gz",
		filename: "embedded-addons.win32-x64.tar.gz",
		filePath: archivePath,
	},
	files: [
		{ variant: "baseline", filename: "pi_natives.win32-x64-baseline.node", size: 150683136 },
	],
};
